pipeline {
    agent any
    tools{
        jdk 'JDK21'
        maven'3.9.11'
         
    }
    options {
        skipStagesAfterUnstable()
    }

    stages {

        stage('Install maven') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Build') {
            steps {
                
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }



        stage('Build Finish') {
            steps {
                echo 'Build success'
            }
        }
    }
    post    {
            {      
            success {
            echo "Build zakończony sukcesem! ✅"
            }
            failure {
            echo "Build się wysypał 😬"
            }
            always {
            echo "Ten krok wykona się zawsze, niezależnie od wyniku."
            }
        }
    }   
}
